MadPlotter:
  # -n, --count arg      Number of plots to create (default = 1, -1 = infinite)
  # -r, --threads arg    Number of threads (default = 4)
  # -u, --buckets arg    Number of buckets (default = 256)
  # -v, --buckets3 arg   Number of buckets for phase 3+4 (default = buckets)
  # -t, --tmpdir arg     Temporary directory, needs ~220 GiB (default = $PWD)
  # -2, --tmpdir2 arg    Temporary directory 2, needs ~110 GiB [RAM] (default = <tmpdir>)
  # -d, --finaldir arg   Final directory (default = <tmpdir>)
  # -w, --waitforcopy    Wait for copy to start next plot
  # -p, --poolkey arg    Pool Public Key (48 bytes)
  # -c, --contract arg   Pool Contract Address (62 chars)
  # -f, --farmerkey arg  Farmer Public Key (48 bytes)
  # -G, --tmptoggle      Alternate tmpdir/tmpdir2 (default = false)
  # -K, --rmulti2 arg    Thread multiplier for P2 (default = 1)
  # --help           Print help
  # Note: tmp and destination path must have trail "/"
  # Note 2: To plot for pools, specify <contract> address via -c instead of <poolkey>, see chia plotnft show
  PlotterPath: '/home/username/madmax/build/chia_plot'
  r: 16
  u: 
  v: 
  t: '/mnt/tmp1/'
  2: '/mnt/tmp2/'
  d:
    - '/mnt/disk1/'
    - '/mnt/disk2/'
  w: 
  p: 
  c: ''
  f: ''
  G: 
  K: 

Main:
  PlotSize: 108797952330 # MadMax plot's size in bytes